version: '3.8'

services:
  atmos-receptor:
    build: .
    container_name: atmos-receptor
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_TOPIC: ${MQTT_TOPIC}
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/receptor/logs
